language: node_js
node_js:
  - lts/*
addons:
  chrome: stable # make Chrome available
before_install:
  - yarn global add @lhci/cli@0.3.x # install LHCI
branches:
  only:
    - "master"
script:
  - yarn run build # build your site
  - yarn test # run your normal tests
after_success:
  - lhci autorun --upload.target=temporary-public-storage --perf=95 # run lighthouse CI against your static site

